# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
