# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 08:50
from __future__ import unicode_literals

from mezzanine.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memebot', '0002_auto_20170421_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
