#!/usr/bin/env python

from optparse import OptionParser
import sys
import os

sys.dont_write_bytecode = True

import madcow

__usage__ = '%prog [-b <basedir>]'
__doc__ = 'Run the Madcow infobot'

DEFAULT_BASE = os.path.realpath(os.path.join(os.environ.get('HOME', ''), '.madcow'))

def main(argv=None):
    optparse = OptionParser(__usage__, version=madcow.__version__, description=__doc__)
    optparse.add_option('-b', '--base', metavar='<dir>', default=DEFAULT_BASE, help='madcow base (%default)')
    opts, args = optparse.parse_args(argv)
    if args:
        optparse.error('%prog expects no arguments')
    try:
        madcow.run(base=opts.base)
    except Exception, error:
        print >> sys.stderr, 'Error: %s' % error
        return 1
    return 0

if __name__ == '__main__':
    sys.exit(main())
