#!/usr/bin/env python

from optparse import OptionParser
import sys
import os
import madcow

madcow = type('masdf', (object,), {'__version__': '0.1'})()

__usage__ = '%prog [-b <basedir>] [section:key=val ...]'
__doc__ = 'Run the Madcow infobot'

DEFAULT_BASE = os.path.realpath(os.path.join(os.environ.get('HOME', ''), '.madcow'))

def main(argv=None):
    optparse = OptionParser(__usage__, version=madcow.__version__, description=__doc__)
    optparse.add_option('-b', '--base', metavar='<dir>', default=DEFAULT_BASE, help='madcow base (%default)')
    opts, args = optparse.parse_args(argv)
    settings = {}
    for arg in args:
        try:
            section, setting = arg.split(':', 1)
            key, val = setting.split('=', 1)
        except ValueError:
            optparse.error('format for setting overrides is: section:key=val')
        settings.setdefault(section, {})[key] = val
    madcow.run(base=opts.base, settings=settings)
    return 0

if __name__ == '__main__':
    sys.exit(main())
